title: Xinru Wang's Homepage
page-top-title: Xinru Wang
top-section-bg-text: Data Analytics & Finance
home-subtitle: About Me
publications-subtitle: '<i class="bi bi-file-text-fill"></i>&nbsp;PUBLICATIONS'
awards-subtitle: '<i class="bi bi-award-fill"></i>&nbsp;AWARDS'
copyright-text: '&copy; Xinru Wang 2024. All Rights Reserved.'
github-link: https://github.com/Xinru-99
license-link: https://github.com/Xinru-99/Xinru-99.github.io/blob/main/LICENSE
