title: Xinru Wang's Homepage
page-top-title: Xinru Wang
top-section-bg-text: Data Analytics & Finance
home-subtitle: Xinru Wang&ensp;|&ensp;王心如
copyright-text: '&copy; Xinru Wang 2024. All Rights Reserved.'
